export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
export const FETCHING_USER_INFO = 'FETCHING_USER_INFO'
export const FETCHING_USER_INFO_SUCCESS = 'FETCHING_USER_INFO_SUCCESS'
export const FETCHING_USER_INFO_ERROR = 'FETCHING_USER_INFO_ERROR'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCESS = 'LOGIN_SUCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

