export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'

export const FETCHING_REQUEST_TOKEN = 'FETCHING_REQUEST_TOKEN'

export const FETCHING_SESSION = 'FETCHING_SESSION'
export const FETCHING_SESSION_SUCCESS = 'FETCHING_SESSION_SUCCESS'
export const FETCHING_SESSION_ERROR = 'FETCHING_SESSION_ERROR'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCESS = 'LOGIN_SUCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SEARCHING_VIDEO = 'SEARCHING_VIDEO'
export const SEARCHING_VIDEO_SUCCESS = 'SEARCHING_VIDEO_SUCCESS'
export const SEARCHING_VIDEO_ERROR = 'SEARCHING_VIDEO_ERROR'

export const GET_VIDEO_DETAIL = 'GET_VIDEO_DETAIL'
export const GET_VIDEO_DETAIL_SUCCESS = 'GET_VIDEO_DETAIL_SUCCESS'
export const GET_VIDEO_DETAIL_ERROR = 'GET_VIDEO_DETAIL_ERROR'
