export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'

export const FETCHING_REQUEST_TOKEN = 'FETCHING_REQUEST_TOKEN'

export const FETCHING_SESSION = 'FETCHING_SESSION'
export const FETCHING_SESSION_SUCCESS = 'FETCHING_SESSION_SUCCESS'
export const FETCHING_SESSION_ERROR = 'FETCHING_SESSION_ERROR'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REQUEST_GENRELIST = 'REQUEST_GETLIST'
export const GENRELIST_SUCCESS = 'GENRELIST_SUCCESS'
export const GENRELIST_ERROR = 'GENRELIST_ERROR'

export const REQUEST_TRENDINGLIST = 'REQUEST_TRENDINGLIST'
export const TRENDINGLIST_SUCCESS = 'TRENDINGLIST_SUCCESS'
export const TRENDINGLIST_ERROR = 'TRENDINGLIST_SUCCESS'

export const REQUEST_ACCDETAIL = 'REQUEST_ACCDETAIL'
export const ACCDETAIL_SUCCESS = 'ACCDETAIL_SUCCESS'
export const ACCDETAIL_ERROR = 'ACCDETAIL_ERROR'

export const REQUEST_FAVORITELIST = 'REQUEST_FAVORITELIST'
export const FAVORITELIST_SUCCESS = 'FAVORITELIST_SUCCESS'
export const FAVORITELIST_ERROR = 'FAVORITELIST_ERROR'

export const REQUEST_MARK = 'REQUEST_MARK'
export const MARK_SUCCESS = 'MARK_SUCCESS'
export const MARK_ERROR = 'MARK_ERROR'
// export const MARK_REMOVE = 'MARK_REMOVE'
// export const MARK_ADD = 'MARK_ADD'
